custom_subs = {
    'analyst': ['sys_analyst', 'data_analyst', 'data_scientist', 'ba'],
    'backend': ['go', 'python', 'c', 'php', 'java', 'ruby', 'scala', 'net', 'nodejs', 'laravel', 'golang', 'delphi', 'abap', 'ml', 'data_engineer', 'unity', 'one_c', 'embedded', 'back-end'],
    'designer': ['ui_ux', 'motion', 'dd', 'ddd', 'game_designer', 'illustrator', 'graphic', 'uxre_searcher'],
    'devops': [],
    'frontend': ['vue', 'react', 'angular', 'wordpress', 'bitrix', 'joomla', 'drupal', 'front-end'],
    'game': [],
    'hr': [],
    'marketing': ['smm', 'copywriter', 'seo', 'link_builder', 'media_buyer', 'email_marketer', 'context', 'content_manager', 'tech_writer'],
    'mobile': ['ios', 'android', 'cross_mobile', 'flutter', 'react_native'],
    'pm': ['project', 'product'],
    'qa': ['manual_qa', 'aqa'],
    'sales_manager': [],
    'junior': [],
    'support': [],
    'hardware': [],
    'security': []
}

name_professions = {
    'analyst': 'Аналитики',
    'backend': 'Backend разработчики',
    'bac-kend': 'Back-end разработчики',
    'designer': 'Дизайнеры',
    'devops': 'DevOps',
    'frontend': 'Frontend разработчики',
    'front-end': 'Front-end разработчики',
    'game': 'Game разработчики',
    'hr': 'HR',
    'marketing': 'Маркетологи',
    'mobile': 'Mobile разработчики',
    'pm': 'Product & project менеджеры',
    'qa': 'QA',
    'sales_manager': 'Sales',
    'junior': 'Junior',
    'sys_analyst': 'Системные аналитики',
    'data_analyst': 'Аналитики данных',
    'data_scientist': 'Сециалисты по работе с данными',
    'ba': 'Бизнес аналитики',
    'python': 'Python разработчики',
    'c': 'C family разработчики',
    'php': 'PHP разработчики',
    'java': 'Java разработчики',
    'ruby': 'Ruby разработчики',
    'scala': 'Scala разработчики',
    'net': 'NET разработчики',
    'nodejs': 'NodeJs разработчики',
    'laravel': 'Laravel разработчики',
    'go': 'Golang разработчики',
    'golang': 'Golang разработчики',
    'delphi': 'Delphi разработчики',
    'abap': 'Abap разработчики',
    'ml': 'ML разработчики',
    'data_engineer': 'Data engineer',
    'unity': 'Unity разработчики',
    'one_c': '1С разработчики',
    'embedded': 'Embedded разработчики',
    'ui_ux': 'UX/UI дизайнеры',
    'ux_ui': 'UX/UI дизайнеры',
    'motion': 'Motion дизайнеры',
    'dd': '2D дизайнеры',
    'ddd': '3D дизайнеры',
    'game_designer': 'Дизайнеры игр',
    'illustrator': 'Иллюстраторы',
    'graphic': 'Графичекие дизайнеры',
    'uxre_searcher': 'uxre_searcher',
    'vue': 'Vue разработчики',
    'react': 'React разработчики',
    'angular': 'Angular разработчики',
    'wordpress': 'Wordpress разработчики',
    'bitrix': 'Bitrix разработчики',
    'joomla': 'Joomla разработчики',
    'drupal': 'Drupal разработчики',
    'project': 'Project менеджеры',
    'product': 'Product менеджеры',
    'manual_qa': 'Мануальные тестировщики',
    'aqa': 'QA',
    'support': 'Support',
    'ios': 'IOS разработчик',
    'android': 'Android разработчик',
    'cross_mobile': 'Cross Mobile',
    'flutter': 'Flutter разработчик',
    'react_native': 'React Native разработчик',
    'smm': 'SMM',
    'copywriter': 'Copywriter',
    'seo': 'SEO',
    'link_builder': 'Link builder',
    'media_buyer': 'Media buyer',
    'email_marketer': 'Email marketer',
    'context': 'Context',
    'content_manager': 'Content manager',
    'tech_writer': 'Tech writer',
    'marketplace': 'Marketplace',
    'security': 'Security',
    'hardware': 'Hardware'
}
